# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Test3
        run: env | sort
        
      - name: Test4
        run: git status
      
      - name: Create new branch
        uses: actions/create-branch@v2
        with:
          branch: new-feature
          commit-message: 'Initial commit for new feature'
          commit-author: 'Your Name <youremail@example.com>'
        
#      - name: Test5
#        run: |
#          echo 1A
#          git config --global user.email "mateus.b.benedito@gmail.com"
#          echo 1B
#          git config --global user.name "mateusbbenedito"
#          echo 1C
#          git checkout -b feature/teste
#          echo 2 $GITHUB_TOKEN
#          git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/OWNER/REPO.git
#          git commit -m 'teste'
#          echo 3
#          git push
#          echo 4
