# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Versão: (ex: 1.0.0)'
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      - name: List env
        run: env | sort
        
      - name: Create release branch
        run: |
          git checkout -b release/v${{ github.event.inputs.versionName }}
          git status
      
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      
#      - name: Test5
#        run: |
#          echo 1A
#          git config --global user.email "mateus.b.benedito@gmail.com"
#          echo 1B
#          git config --global user.name "mateusbbenedito"
#          echo 1C
#          git checkout -b feature/teste
#          echo 2 $GITHUB_TOKEN
#          git remote add origin https://x-access-token:$GITHUB_TOKEN@github.com/OWNER/REPO.git
#          git commit -m 'teste'
#          echo 3
#          git push
#          echo 4
