name: printEnv

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: Open checkout
        uses: actions/checkout@v2
      - name: Print Env
        run: env | sort
